# Generated by Django 5.1b1 on 2024-07-22 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cat1', models.CharField(max_length=200)),
                ('cat2', models.CharField(max_length=200)),
                ('wikiLink', models.URLField(max_length=500)),
                ('rock_star', models.BooleanField(default=False)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('youtubeLink', models.URLField(max_length=500)),
                ('ranking', models.IntegerField()),
                ('type', models.CharField(max_length=200)),
                ('cat1', models.CharField(max_length=200)),
                ('cat2', models.CharField(max_length=200)),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField()),
                ('startTimeCode', models.CharField(max_length=8)),
                ('questionsTimeCode', models.CharField(max_length=8)),
                ('length', models.CharField(max_length=8)),
                ('audioQuality', models.CharField(max_length=50)),
                ('videoQuality', models.CharField(max_length=50)),
                ('tnLink', models.URLField(max_length=500)),
                ('publishDate', models.DateTimeField()),
                ('insertDate', models.DateTimeField(auto_now_add=True)),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conf_app.speaker')),
            ],
        ),
    ]
