# Generated by Django 5.1b1 on 2024-07-22 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conf_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conf',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='speaker',
            old_name='rock_star',
            new_name='rockStar',
        ),
    ]
