# Generated by Django 5.1b1 on 2024-07-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf_app', '0002_rename_title_conf_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conf',
            name='cat2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='cat2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
