# Generated by Django 5.1b1 on 2024-07-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf_app', '0003_alter_conf_cat2_alter_speaker_cat2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='wikiLink',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
