# Generated by Django 5.1b1 on 2024-07-22 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conf_app', '0004_alter_speaker_wikilink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conf',
            name='date',
        ),
    ]
