# Generated by Django 5.1b1 on 2024-07-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf_app', '0005_remove_conf_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conf',
            name='audioQuality',
            field=models.CharField(default='High', max_length=50),
        ),
        migrations.AlterField(
            model_name='conf',
            name='length',
            field=models.CharField(blank=True, default='00:00:00', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='conf',
            name='questionsTimeCode',
            field=models.CharField(blank=True, default='00:00:00', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='conf',
            name='ranking',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='conf',
            name='startTimeCode',
            field=models.CharField(default='00:00:00', max_length=8),
        ),
        migrations.AlterField(
            model_name='conf',
            name='tags',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='conf',
            name='tnLink',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='conf',
            name='type',
            field=models.CharField(default='Conférence', max_length=200),
        ),
        migrations.AlterField(
            model_name='conf',
            name='videoQuality',
            field=models.CharField(default='High', max_length=50),
        ),
    ]
