# Generated by Django 5.1b1 on 2024-07-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf_app', '0006_alter_conf_audioquality_alter_conf_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conf',
            name='publishDate',
            field=models.DateField(),
        ),
    ]
