# Generated by Django 5.1b1 on 2024-07-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf_app', '0007_alter_conf_publishdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='conf',
            name='youtubeEmbedLink',
            field=models.URLField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
