# Generated by Django 5.1b1 on 2024-07-31 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf_app', '0008_conf_youtubeembedlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='quotes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
