# Generated by Django 5.1b1 on 2024-08-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf_app', '0009_speaker_quotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conf',
            name='tnLink',
            field=models.URLField(blank=True, default='https://i.ibb.co/5r6cVCW/confrencesfr-high-resolution-logo.png', max_length=500, null=True),
        ),
    ]
